### PR TITLE
feat(dlang): Add a D host SDK

### PR DESCRIPTION
**Pull request by chances**
See [dlang.org](https://dlang.org).

### CODE REVIEW

**Comment by nilslice** [comment]
Wow, @chances - this is awesome! Thank you 🙏 we will review asap and get back to you with any questions.

**Comment by zshipko** [comment]
Nice! As far as I can tell this code makes sense, but I don't really know D and didn't see any tests or anything to run. Definitely curious to try it out!

As part of our push toward Extism 1.0 (see https://github.com/extism/extism/issues/42) we're looking to move the SDKs into their own repos, it might be a good idea to start this off in its own repo to begin with?

**Comment by chances** [comment]
> Nice! As far as I can tell this code makes sense, but I don't really know D and _didn't see any tests or anything to run_. Definitely curious to try it out!
> 
> ...

(Emphasis added)

I totally plan to add unit tests (D let you define them inline, which is crazy convenient), but I haven't made time for this step yet. I've added a TODO list to the PR description.

**Comment by chances** [comment]
> ...
> 
> As part of our push toward Extism 1.0 (see #42) we're looking to move the SDKs into their own repos, it might be a good idea to start this off in its own repo to begin with?

Is there an extant repo or an example you can point me to to try this out?

**Comment by zshipko** [comment]
> > ...
> > As part of our push toward Extism 1.0 (see #42) we're looking to move the SDKs into their own repos, it might be a good idea to start this off in its own repo to begin with?
> 
> Is there an extant repo or an example you can point me to so I can try this out without flailing in the dark? What is the procedure for getting a new repo added to the @extism org?

We haven't fully discussed that process yet, but I think we could create the `extism/d-sdk` repo from the start to avoid the "flailing in the dark" issue - soon we'll also be splitting apart the languages into their own repos so it won't feel so isolated at that point. 

I'll bring this up at our team meeting on Monday!

**Comment by chances** [comment]
@zshipko Were y'all able to discuss the SDKs-in-separate-repos issue this week?

**Comment by zshipko** [comment]
Ah yes, sorry! 

We decided that since the process of extracting the SDKs into their own repos would happen gradually it would still make sense to merge this into the current repo.

We are also hoping to make all the new SDK repos have a common interface for building/testing. Since this doesn't exist yet we don't want to hold you up!

Also, none of us are D users and we probably need some additional help with understanding D package management and how to setup github actions for testing/releases.

**Comment by chances** [comment]
@zshipko Thank you.

D has a standard package manager (Dub) and a common repo of packages: [code.dlang.org](https://code.dlang.org). Either I or one of your administrators will login to the package repo and register this repo as a D package once the PR is merged.

I am setting up a D continuous integration script as we speak.

**Comment by chances** [comment]
The example fails at runtime:

```
stop reason = EXC_BAD_ACCESS
frame #0: 0x0000000101150a79 libextism.dylib`extism_runtime::manifest::Manifest::new::hd10fbb1ab9120ad8 + 105
frame #1: 0x0000000101162d84 libextism.dylib`extism_runtime::plugin::Plugin::new::hd1dc56981df79447 + 404
frame #2: 0x000000010124aead libextism.dylib`extism_runtime::context::Context::new_plugin::hc510f639ef593a32 + 29
frame #3: 0x00000001011521a7 libextism.dylib`extism_plugin_new + 343
frame #4: 0x000000010001c749 extism_hello`_D6extism6Plugin6__ctorMFNcxAhAPxS3__C14ExtismFunctionbZSQCdQBz(this=0x0000000102800000, withWasi=false, functions=const(runtime.ExtismFunction)*[] @ 0x00007ff7bfefe860, wasm=(length = 18635, ptr = "")) at extism.d:157
frame #5: 0x0000000100002b00 extism_hello`_Dmain at app.d:12
```

**Comment by zshipko** [comment]
When I try to run the example on Linux using `dub run extism:hello` from the root of the repo I get this error:
```
    Building package extism:hello in /home/zach/devel/extism/extism/d/examples/hello/
    Starting Performing "debug" build using dmd for x86_64.
    Building extism:hello 0.5.0+commit.27.g98e9ca5: building configuration [application]
Error: unrecognized switch '-P-I/home/zach/devel/extism/extism'
       run `dmd` to print the compiler manual
       run `dmd -man` to open browser on manual
Error dmd failed with exit code 1.
```

Could I be on the wrong version of `dmd` or something? I just installed the latest from nix, which is 2.100.2.

File: d/extism.d [hunk 1]
```diff
@@ -0,0 +1,258 @@
...
+///     outputs: return values
+///     data: user data associated with the host function
+alias FunctionType = void delegate(
+  CurrentPlugin plugin, const Val[] inputs, Val[] outputs, void* data
+);
+
+/// Returns: A slice of an allocated memory block of the currently running plugin.
+ubyte[] memory(CurrentPlugin plugin, ulong n) {
+  auto length = extism_current_plugin_memory_length(cast(ExtismCurrentPlugin*) plugin, n);
+  return extism_current_plugin_memory(cast(ExtismCurrentPlugin*) plugin)[n .. length];
```
Comment (zshipko) [inline d/extism.d:64]: I think this should be:

```suggestion
  return extism_current_plugin_memory(cast(ExtismCurrentPlugin*) plugin)[n .. n + length];
```

I don't know the language very well, so sorry if that's incorrect. I'm just going through the code-path that would be executed and looking for any potential issues.

**Comment by chances** [comment]
> When I try to run the example on Linux using `dub run extism:hello` from the root of the repo I get this error:
> 
> ...
> 
> Could I be on the wrong version of `dmd` or something? I just installed the latest from nix, which is 2.100.2.

I'm using `dmd` v2.103.0 on mac OS.

Regardless, it's likely that my use of ImportC's automatic preprocessor flags were introduced in a later D version. I'm updating the toolchain requirements to specify version `>=2.102` of the D frontend.

D's download docs recommended running `nix-env -iA nixpkgs.dmd` in a Nix environment.

**Comment by zshipko** [comment]
Thanks, I just ended up downloading dmd from the dlang website and it seems to be working now - with this diff the example also seems to run succesfully!

```
diff --git a/d/examples/hello/source/app.d b/d/examples/hello/source/app.d
index 35b2d9b..e945c05 100644
--- a/d/examples/hello/source/app.d
+++ b/d/examples/hello/source/app.d
@@ -13,7 +13,7 @@ void main() {
                Function!string(
                        "hello_world", /* Inputs */ [ValType.i64], /* Outputs */ [ValType.i64], toDelegate(&helloWorld), "Hello, again!"
                ),
-       ]);
+       ], true);
 
        auto input = "aeiou";
        plugin.call("count_vowels", cast(ubyte[]) input.representation);
diff --git a/d/extism.d b/d/extism.d
index ba4752a..3c3ddea 100644
--- a/d/extism.d
+++ b/d/extism.d
@@ -61,7 +61,7 @@ alias FunctionType = void delegate(
 /// Returns: A slice of an allocated memory block of the currently running plugin.
 ubyte[] memory(CurrentPlugin plugin, ulong n) {
   auto length = extism_current_plugin_memory_length(cast(ExtismCurrentPlugin*) plugin, n);
-  return extism_current_plugin_memory(cast(ExtismCurrentPlugin*) plugin)[n .. length];
+  return extism_current_plugin_memory(cast(ExtismCurrentPlugin*) plugin)[n .. n + length];
 }
 
 /// Allocate a memory block in the currently running plugin.
```

It seems that `withWasi` needs to be set to `true` for the example, and the change to the `memory` function fixes this error I was getting initially:

```
fatal runtime error: Rust cannot catch foreign exceptions
Error Program exited with code -6
```

**Comment by chances** [comment]
@extism Have any of you been able to test this again?

**Comment by mhmd-azeez** [comment]
@chances this is what I get when I try to test the library:
```
(dmd-2.105.2)mo@mo-laptop:/mnt/d/dylibso/x/extism$ dub lint
    Starting Performing "debug" build using /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd for x86_64.
  Up-to-date emsi_containers 0.9.0: target for configuration [library] is up to date.
  Up-to-date libdparse 0.23.2: target for configuration [library] is up to date.
  Up-to-date dcd:dsymbol 0.16.0-beta.2: target for configuration [library] is up to date.
  Up-to-date inifiled 1.3.3: target for configuration [library-quiet] is up to date.
  Up-to-date libddoc:common 0.8.0: target for configuration [library] is up to date.
  Up-to-date libddoc 0.8.0: target for configuration [lib] is up to date.
  Up-to-date dscanner 0.15.2: target for configuration [application] is up to date.
    Finished To force a rebuild of up-to-date targets, run again with --force
     Running ../../../../../home/mo/.dub/packages/dscanner/0.15.2/dscanner/bin/dscanner --config /mnt/d/dylibso/x/extism/dscanner.ini --styleCheck /mnt/d/dylibso/x/extism/
(dmd-2.105.2)mo@mo-laptop:/mnt/d/dylibso/x/extism$ dub test
             Generating test runner configuration 'extism-test-library' for 'library' (sourceLibrary).
    Starting Performing "unittest" build using /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd for x86_64.
    Building extism 0.5.0+commit.41.gbe7d5d2: building configuration [extism-test-library]
d/extism.d(11,9): Error: undefined identifier `I32`, did you mean enum member `f32`?
d/extism.d(12,9): Error: undefined identifier `I64`, did you mean enum member `f64`?
d/extism.d(13,9): Error: undefined identifier `F32`, did you mean enum member `f32`?
d/extism.d(14,9): Error: undefined identifier `F64`, did you mean enum member `f64`?
d/extism.d(15,10): Error: undefined identifier `V128`, did you mean enum member `v128`?
d/extism.d(16,13): Error: undefined identifier `FuncRef`, did you mean enum member `funcRef`?
d/extism.d(17,15): Error: undefined identifier `ExternRef`, did you mean enum member `externRef`?
d/extism.d(145,17): Error: undefined identifier `ExtismPlugin`
d/extism.d(154,3): Error: undefined identifier `ExtismFunction`
Error /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd failed with exit code 1.
(dmd-2.105.2)mo@mo-laptop:/mnt/d/dylibso/x/extism$ dub run extism:hello
             Building package extism:hello in /mnt/d/dylibso/x/extism/d/examples/hello/
    Starting Performing "debug" build using /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd for x86_64.
    Building extism:hello 0.5.0+commit.41.gbe7d5d2: building configuration [application]
d/extism.d(11,9): Error: undefined identifier `I32`, did you mean enum member `f32`?
d/extism.d(12,9): Error: undefined identifier `I64`, did you mean enum member `f64`?
d/extism.d(13,9): Error: undefined identifier `F32`, did you mean enum member `f32`?
d/extism.d(14,9): Error: undefined identifier `F64`, did you mean enum member `f64`?
d/extism.d(15,10): Error: undefined identifier `V128`, did you mean enum member `v128`?
d/extism.d(16,13): Error: undefined identifier `FuncRef`, did you mean enum member `funcRef`?
d/extism.d(17,15): Error: undefined identifier `ExternRef`, did you mean enum member `externRef`?
d/extism.d(145,17): Error: undefined identifier `ExtismPlugin`
d/extism.d(154,3): Error: undefined identifier `ExtismFunction`
Error /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd failed with exit code 1.
(dmd-2.105.2)mo@mo-laptop:/mnt/d/dylibso/x/extism$
```

Am I missing something?

**Comment by mhmd-azeez** [comment]
Also, it seems like `dub lint` conflicts with rust since they both use the `targets` folder. `dub lint` complains about rust's intermediate files there:

```
(dmd-2.105.2)mo@mo-laptop:/mnt/d/dylibso/x/extism$ dub lint
    Starting Performing "debug" build using /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd for x86_64.
  Up-to-date emsi_containers 0.9.0: target for configuration [library] is up to date.
  Up-to-date libdparse 0.23.2: target for configuration [library] is up to date.
  Up-to-date dcd:dsymbol 0.16.0-beta.2: target for configuration [library] is up to date.
  Up-to-date inifiled 1.3.3: target for configuration [library-quiet] is up to date.
  Up-to-date libddoc:common 0.8.0: target for configuration [library] is up to date.
  Up-to-date libddoc 0.8.0: target for configuration [lib] is up to date.
  Up-to-date dscanner 0.15.2: target for configuration [application] is up to date.
    Finished To force a rebuild of up-to-date targets, run again with --force
     Running ../../../../../home/mo/.dub/packages/dscanner/0.15.2/dscanner/bin/dscanner --config /mnt/d/dylibso/x/extism/dscanner.ini --styleCheck /mnt/d/dylibso/x/extism/
/mnt/d/dylibso/x/extism/target/release/build/ahash-d3a712fdc7a3fa49/build_script_build-d3a712fdc7a3fa49.d(1:2)[error]: Expected `identifier` instead of `:`
/mnt/d/dylibso/x/extism/target/release/build/ahash-d3a712fdc7a3fa49/build_script_build-d3a712fdc7a3fa49.d(5:88)[error]: invalid variable declaration or function declaration
/mnt/d/dylibso/x/extism/target/release/build/ahash-d3a712fdc7a3fa49/build_script_build-d3a712fdc7a3fa49.d(1:120)[warn]: Line is longer than 120 characters
/mnt/d/dylibso/x/extism/target/release/build/ahash-d3a712fdc7a3fa49/build_script_build-d3a712fdc7a3fa49.d(3:120)[warn]: Line is longer than 120 characters
/mnt/d/dylibso/x/extism/target/release/build/anyhow-2ae0f44e6a44faa0/build_script_build-2ae0f44e6a44faa0.d(1:2)[error]: Expected `identifier` instead of `:`
/mnt/d/dylibso/x/extism/target/release/build/anyhow-2ae0f44e6a44faa0/build_script_build-2ae0f44e6a44faa0.d(5:88)[error]: invalid variable declaration or function declaration
/mnt/d/dylibso/x/extism/target/release/build/anyhow-2ae0f44e6a44faa0/build_script_build-2ae0f44e6a44faa0.d(1:120)[warn]: Line is longer than 120 characters
/mnt/d/dylibso/x/extism/target/release/build/anyhow-2ae0f44e6a44faa0/build_script_build-2ae0f44e6a44faa0.d(3:120)[warn]: Line is longer than 120 characters
/mnt/d/dylibso/x/extism/target/release/build/async-trait-d13ce710d56882fa/build_script_build-d13ce710d56882fa.d(1:2)[error]: Expected `identifier` instead of `:`
/mnt/d/dylibso/x/extism/target/release/build/async-trait-d13ce710d56882fa/build_script_build-d13ce710d56882fa.d(5:93)[error]: invalid variable declaration or function declaration
/mnt/d/dylibso/x/extism/target/release/build/async-trait-d13ce710d56882fa/build_script_build-d13ce710d56882fa.d(1:120)[warn]: Line is longer than 120 characters
/mnt/d/dylibso/x/extism/target/release/build/async-trait-d13ce710d56882fa/build_script_build-d13ce710d56882fa.d(3:120)[warn]: Line is longer than 120 characters
.... more errors
```

**Comment by chances** [comment]
> Also, it seems like `dub lint` conflicts with rust since they both use the `targets` folder. `dub lint` complains about rust's intermediate files there:
>
> [sic]

Dub does _not_ conflict with the `targets` folder. It is likely scanning every file with the `*.d` extension.

Does this occur if you clean `*.d` files from the `targets` folder?

**Comment by chances** [comment]
> @chances this is what I get when I try to test the library:
> 
> ```
> (dmd-2.105.2)mo@mo-laptop:/mnt/d/dylibso/x/extism$ dub test
>              Generating test runner configuration 'extism-test-library' for 'library' (sourceLibrary).
>     Starting Performing "unittest" build using /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd for x86_64.
>     Building extism 0.5.0+commit.41.gbe7d5d2: building configuration [extism-test-library]
> d/extism.d(11,9): Error: undefined identifier `I32`, did you mean enum member `f32`?
> d/extism.d(12,9): Error: undefined identifier `I64`, did you mean enum member `f64`?
> d/extism.d(13,9): Error: undefined identifier `F32`, did you mean enum member `f32`?
> d/extism.d(14,9): Error: undefined identifier `F64`, did you mean enum member `f64`?
> d/extism.d(15,10): Error: undefined identifier `V128`, did you mean enum member `v128`?
> d/extism.d(16,13): Error: undefined identifier `FuncRef`, did you mean enum member `funcRef`?
> d/extism.d(17,15): Error: undefined identifier `ExternRef`, did you mean enum member `externRef`?
> d/extism.d(145,17): Error: undefined identifier `ExtismPlugin`
> d/extism.d(154,3): Error: undefined identifier `ExtismFunction`
> Error /home/mo/dlang/dmd-2.105.2/linux/bin64/dmd failed with exit code 1.
> ```
>
> Am I missing something?

These symbols are defined in `runtime/extism.h`. This sounds like some issue with how `d/runtime.c` was automatically preprocessed by the D compiler.

This issue does not occur in CI. What OS are you testing on?

**Comment by mhmd-azeez** [comment]
> The lint task succeeds in my testing. If you clean *.d files from the targets folder does dub lint succeed?
Yes.

> These symbols are defined in runtime/extism.h. This sounds like some issue with how d/runtime.c was automatically preprocessed by the D compiler.

> This issue does not occur in CI.

> @mhmd-azeez What OS are you testing on?

I am using WSL, probably windows and linux binaries are mixed. Will try it out on pure linux later on

**Comment by chances** [comment]
I've spawned https://github.com/dlang-community/D-Scanner/issues/932 to address the linting issues with intermediate targets.

**Review by zshipko — COMMENTED** [review]
> These symbols are undefined in the latest release ([v0.5.0](https://github.com/extism/extism/releases/tag/v0.5.0)):

Those symbols aren't available in any release yet, I think it makes sense to target the main branch for now.

I was able to run the example successfully on Linux, and the code looks good!

What do you think is needed for this to be considered ready?

**Comment by chances** [comment]
@zshipko
> > These symbols are undefined in the latest release ([v0.5.0](https://github.com/extism/extism/releases/tag/v0.5.0)):
> 
> Those symbols aren't available in any release yet, I think it makes sense to target the main branch for now.
> 
> I was able to run the example successfully on Linux, and the code looks good!

I am unable to successfully run the example on my macOS machine because the cargo package fails to compile. Is there a specific version of rust I ought be using?

> What do you think is needed for this to be considered ready?

I suppose we can iterate more on the unit tests. In lieu of that:

- Who will be in charge of maintaining the D package in the [D package registry](https://code.dlang.org)? Someone will just need to add the repo to the registry, i.e. https://github.com/extism/extism, and the registry will keep the package updated automatically when new release tags are pushed. We can also include the project's logo. (Where is this asset, by the way?)

    I can do this if you need.

- How shall we amend the website to include D? For example, on the [Integrate into your codebase](https://extism.org/docs/category/integrate-into-your-codebase) page?

**Comment by zshipko** [comment]
> I am unable to successfully run the example on my macOS machine because the cargo package fails to compile. Is there a specific version of rust I ought be using?

`stable` should work, it looks like the latest wasmtime release requires ` 1.70.0` (see https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#changed-1)

> Who will be in charge of maintaining the D package in the [D package registry](https://code.dlang.org/)?

We would definitely appreciate your help with this! I will look into the process a little more.

> How shall we amend the website to include D? 

We are very close to opening up to docs website for contributions, so if you are up to it we would be happy to have someone familiar with the language help with the docs. But working toward 1.0 we are trying to move all the docs closer to the actual code. So if D has a specific way of handling documentation it would be best to use that for now, especially if it's something that can be checked automatically when running the tests. Since the goal is to move the D code to it's own repo, we could even have an Action to publish the docs if needed.

**Comment by chances** [comment]
@zshipko I have the example working locally after I upgraded my rust installation.

**Comment by nilslice** [comment]
Hi @chances -- sorry for hijacking this PR thread, but I have a tangential question for you!

When doing the FFI work for this SDK, did you happen to reference this page of docs? 

https://extism.org/docs/concepts/runtime-apis

Asking as we are in the process of revamping the documentation and considering moving these docs somewhere else. 

Thanks!

**Comment by chances** [comment]
> When doing the FFI work for this SDK, did you happen to reference this page of docs?
> 
> https://extism.org/docs/concepts/runtime-apis

Yes, I referenced that page extensively, especially with relation to the doc comments in the D bindings.

**Comment by bhelx** [comment]
This is looking good to merge to me. Here is what I suggest we do:

1. we can merge
2. we can make a new d-sdk repo and move all the commits to that
3. we can continue work from there

We do have one change we'd like to get in before doing that as mentioned here: https://github.com/extism/extism/pull/511, But also i don't want to block this PR any further. @chances, what do you think? Would you be able to help with the breaking change after we merge?

**Comment by chances** [comment]
@bhelx Yes, that sounds good to me!

Regarding your question, which breaking change in the linked PR are you referring to? I can certainly help with changes to the D SDK, regardless.

**Comment by bhelx** [comment]
Okay i'm gonna merge this today and move it over to d-sdk repo. Will report back when it's done.

**Comment by bhelx** [comment]
Alright, this repo along with commits has been moved to https://github.com/extism/d-sdk
we will remove this copy in extism/extism soon once we get the docs pointing to the right places.

**Comment by bhelx** [comment]
@chances Thanks! I'll make an issue on the new repo. I'll also drop any other items I think we'll need for 1.0.
